<?php

/**
 * @file
 * Contains social_ex.module.
 */

/**
 * Implements hook_theme().
 */
function social_ex_theme($existing, $type, $theme, $path) {
  return [
    'social_ex_links' => [
      'variables' => [
        'elements' => NULL,
        'list_attributes' => NULL,
      ],
      'template' => 'socialex-links',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */
function social_ex_preprocess_block(&$variables) {
  if ($variables['plugin_id'] === 'social_ex_block') {
    // Ensure that the css class "block-social-ex" always available for block.
    $variables['attributes']['class'][] = 'block-social-ex';
  }
}

/**
 * Implements hook_help().
 */
function social_ex_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.social_ex':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The modules provides a block that display links to share content on various popular social media sites.') . '</p>';
      $output .= '<h3>' . t('Installation') . '</h3>';
      $output .= '<p><label>1.&nbsp;</label>' . t('Install as usual, see <a href=":documentation">installing Drupal modules</a> for further information.', [':documentation' => 'https://www.drupal.org/docs/8/extending-drupal-8/installing-contributed-modules-find-import-enable-configure']) . '</p>';
      $output .= '<p><label>2.&nbsp;</label>' . t('The social links configuration settings are available at: /admin/structure/block.') . '</p>';
      $output .= '<p><label>3.&nbsp;</label>' . t('Help and more information visit: <a href=":github">Github</a> or <a href=":iknowlex">www.iknowlex.com/social_ex</a>', [':github' => 'https://github.com/iknowlex/social_ex', ':iknowlex' => 'http://www.iknowlex.com/social_ex']) . '</p>';

      return $output;
  }
}
